import { createClient } from "@supabase/supabase-js";
import fs from "fs";
const env = Object.fromEntries(fs.readFileSync(".env.local","utf8").split("\n").filter(l=>l.includes("=")&&!l.startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^["']|["']$/g,"")];}));
const url = env.NEXT_PUBLIC_SUPABASE_URL, key = env.SUPABASE_SERVICE_ROLE_KEY;
const db = createClient(url, key, { auth: { persistSession: false } });
const SALON = "9f078a3f-071d-4797-a0cf-e5ab6f3c1d2f";
const out = {};
const s = await db.from("salons").select("name, opening_hours, vacation_start, vacation_end").eq("id", SALON).single();
out.salon = s.data; out.salonErr = s.error?.message;
const st = await db.from("staff_members").select("id, name, is_active").eq("salon_id", SALON);
out.staff = st.data; 
const sch = await db.from("staff_schedules").select("staff_member_id, day_of_week, start_time, end_time, is_working, is_active, is_alternate_week, alternate_week_parity").eq("salon_id", SALON).order("day_of_week");
out.schedules = sch.data; out.schedErr = sch.error?.message;
const now = new Date();
const in8 = new Date(now.getTime() + 8*864e5);
const bk = await db.from("bookings").select("id, starts_at, ends_at, status, guest_name, estimated_price, staff_member_id, services(name_en, duration_minutes)").eq("salon_id", SALON).gte("starts_at", new Date(now.getTime()-2*864e5).toISOString()).lt("starts_at", in8.toISOString()).order("starts_at");
out.bookings = bk.data?.map(b=>({t:b.starts_at, e:b.ends_at, st:b.status, n:b.guest_name, p:b.estimated_price, staff:b.staff_member_id, sv:b.services?.name_en, d:b.services?.duration_minutes}));
out.bookingsErr = bk.error?.message;
const q = await db.from("barber_walkin_queue").select("id, customer_name, status, position, joined_at, started_at").eq("salon_id", SALON).in("status",["waiting","in_chair"]);
out.queue = q.data;
const sv = await db.from("services").select("id, name_en, duration_minutes, price").eq("salon_id", SALON).order("duration_minutes");
out.services = sv.data;
console.log(JSON.stringify(out, null, 1));
