/**
 * src/views/dashboard/revenue-chart.js — Revenue trend and analytics charts.
 *
 * Phase 3 feature: renders bar charts showing revenue trends, top services,
 * and peak hours using the existing CSS chart-bar pattern (no external deps).
 *
 * XSS safety: all user-provided data (service names, etc.) is passed through
 * esc() before innerHTML insertion. Numeric values are formatted with
 * toFixed() / Number() before interpolation.
 */

// ---------------------------------------------------------------------------
// Security helper
// ---------------------------------------------------------------------------

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ---------------------------------------------------------------------------
// Revenue bar chart (30-day daily revenue)
// ---------------------------------------------------------------------------

/**
 * Render a 30-day revenue bar chart into `container`.
 * @param {HTMLElement} container
 * @param {object[]} bookings — booking records from Supabase
 * @param {{ days?, title? }} options
 */
export function renderRevenueChart(container, bookings, {
  days = 30,
  title = 'Umsatz (letzte 30 Tage)',
} = {}) {
  const confirmed = bookings.filter((b) => b.status === 'confirmed');
  const buckets = buildDayBuckets(days);

  confirmed.forEach((b) => {
    const key = b.booking_date;
    if (Object.prototype.hasOwnProperty.call(buckets, key)) {
      buckets[key] += Number(b.service_price) || 0;
    }
  });

  const values = Object.values(buckets);
  const max = Math.max(...values, 1);
  const total = values.reduce((a, b) => a + b, 0);

  // title is a static string from the caller — not user data
  const html = `
    <div class="dash-chart">
      <div class="dash-chart-header">
        <h4 class="dash-chart-title">${esc(title)}</h4>
        <div class="dash-chart-total">CHF ${Number(total).toFixed(2)}</div>
      </div>
      <div class="dash-chart-bars" role="img" aria-label="${esc(title)}">
        ${Object.entries(buckets).map(([date, val]) => {
          // date is generated by buildDayBuckets (ISO string from JS Date) — safe
          const heightPct = ((val / max) * 100).toFixed(1);
          const label = formatShortDate(date);
          const isToday = date === todayStr();
          const valFormatted = Number(val).toFixed(0);
          const valFull = Number(val).toFixed(2);
          return `
            <div class="dash-chart-bar-wrap${isToday ? ' dash-chart-bar-today' : ''}">
              <div class="dash-chart-bar-value">${val > 0 ? `CHF ${valFormatted}` : ''}</div>
              <div class="dash-chart-bar" style="height:${heightPct}%" title="${label}: CHF ${valFull}"></div>
              <div class="dash-chart-bar-label">${label}</div>
            </div>`;
        }).join('')}
      </div>
    </div>`;

  container.innerHTML = html;
}

// ---------------------------------------------------------------------------
// Top services horizontal bar chart
// ---------------------------------------------------------------------------

/**
 * @param {HTMLElement} container
 * @param {{ name: string, count: number }[]} topServices
 */
export function renderTopServicesChart(container, topServices) {
  if (!topServices.length) {
    container.innerHTML = '<p class="dash-chart-empty">Noch keine Daten</p>';
    return;
  }

  const max = Math.max(topServices[0].count || 1, 1);

  const html = `
    <div class="dash-chart">
      <h4 class="dash-chart-title">Top Services</h4>
      <div class="dash-chart-h-bars">
        ${topServices.map(({ name, count }) => {
          // name comes from DB — escape it
          const widthPct = ((Math.max(0, Number(count)) / max) * 100).toFixed(1);
          return `
            <div class="dash-chart-h-row">
              <div class="dash-chart-h-label">${esc(name)}</div>
              <div class="dash-chart-h-track">
                <div class="dash-chart-h-fill" style="width:${widthPct}%"></div>
              </div>
              <div class="dash-chart-h-value">${Number(count).toFixed(0)}\xd7</div>
            </div>`;
        }).join('')}
      </div>
    </div>`;

  container.innerHTML = html;
}

// ---------------------------------------------------------------------------
// Peak hours bar chart
// ---------------------------------------------------------------------------

/**
 * @param {HTMLElement} container
 * @param {number[]} hourCounts — 24-element array (index = hour of day)
 */
export function renderPeakHoursChart(container, hourCounts) {
  const businessHours = (hourCounts || []).slice(8, 21); // 08:00–20:00
  const max = Math.max(...businessHours, 1);

  const html = `
    <div class="dash-chart">
      <h4 class="dash-chart-title">Sto\xdfzeiten</h4>
      <div class="dash-chart-bars">
        ${businessHours.map((count, i) => {
          // i and count are JavaScript numbers — not user data
          const hour = i + 8;
          const heightPct = ((Math.max(0, Number(count)) / max) * 100).toFixed(1);
          const countSafe = Number(count).toFixed(0);
          return `
            <div class="dash-chart-bar-wrap" style="flex:1">
              <div class="dash-chart-bar" style="height:${heightPct}%" title="${hour}:00 \u2014 ${countSafe} Buchungen"></div>
              <div class="dash-chart-bar-label">${hour}</div>
            </div>`;
        }).join('')}
      </div>
    </div>`;

  container.innerHTML = html;
}

// ---------------------------------------------------------------------------
// Helpers (pure JS, no user data)
// ---------------------------------------------------------------------------

function buildDayBuckets(days) {
  const buckets = {};
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    buckets[d.toISOString().slice(0, 10)] = 0;
  }
  return buckets;
}

function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

function formatShortDate(dateStr) {
  const d = new Date(dateStr);
  return `${d.getDate()}.${d.getMonth() + 1}.`;
}
