import {beforeEach,expect,test,vi} from "vitest";
import {generateCategoryListSchema,generateOrganizationSchema,generateWebsiteSchema,safeJsonLd} from "@/lib/seo";
const h=vi.hoisted(()=>({rows:[] as any[],reads:0}));
vi.mock("@/lib/supabase",()=>({createAdminSupabaseClient:()=>({from:()=>{h.reads++;let rows=[...h.rows],head=false;const q:any={select:(_s:string,opts:any)=>{head=!!opts?.head;return q},contains:(k:string,v:string[])=>{rows=rows.filter(r=>v.every(x=>r[k].includes(x)));return q},eq:(k:string,v:any)=>{rows=rows.filter(r=>r[k]===v);return q},or:(filter:string)=>{const key=filter.split(".")[0],expected=filter.endsWith("true");rows=rows.filter(r=>r[key]==null||r[key]===expected);return q},order:()=>q,limit:(n:number)=>{rows=rows.slice(0,n);return q},then:(a:any,b:any)=>Promise.resolve({data:head?null:rows,count:rows.length,error:null}).then(a,b)};return q}})}));
import {getCategorySeo,bustCategorySeoCache} from "@/lib/seo/category-seo-cache";
beforeEach(()=>{bustCategorySeoCache();h.reads=0;h.rows=[];});
test("SEO queries exclude inactive, test and unlisted rows while retaining legacy null visibility",async()=>{h.rows=[{name:"public",categories:["nails"],is_active:true,is_test:false,listed_on_marketplace:true},{name:"legacy",categories:["nails"],is_active:true,is_test:null,listed_on_marketplace:null},{name:"hidden",categories:["nails"],is_active:true,is_test:false,listed_on_marketplace:false},{name:"test",categories:["nails"],is_active:true,is_test:true,listed_on_marketplace:true},{name:"inactive",categories:["nails"],is_active:false},{name:"other",categories:["spa"],is_active:true}];const result=await getCategorySeo("nails");expect(result.count).toBe(2);expect(result.salons.map(s=>s.name)).toEqual(["public","legacy"]);expect(await getCategorySeo("nails")).toBe(result);expect(h.reads).toBe(2);});
test("empty category contains no invented business",async()=>{expect(await getCategorySeo("spa")).toEqual({count:0,salons:[]});});
for(const locale of ["de","en","fr","it"]){test(`${locale} list nests business fields and preserves page URL`,()=>{const s=generateCategoryListSchema("nails",[{name:"Fixture",slug:"fixture",categories:["nails"],average_rating:4.7,review_count:6,address:"Fixture street",postal_code:"4000",cover_photo_url:"/fixture.jpg"}],locale,{url:`https://solen.ch/${locale}/basel/nails`,cityName:"Basel"});expect(s.itemListElement[0]).toMatchObject({"@type":"ListItem",position:1,item:{"@type":"NailSalon",url:`https://solen.ch/${locale}/salon/fixture`,aggregateRating:{ratingValue:4.7,reviewCount:6},address:{streetAddress:"Fixture street",addressLocality:"Basel"}}});expect(s.itemListElement[0]).not.toHaveProperty("aggregateRating");expect(s.url).toBe(`https://solen.ch/${locale}/basel/nails`);});}
test("minimal older callers omit unsourced rating and address",()=>{const s=generateCategoryListSchema("spa",[{name:"Fixture",slug:"fixture",review_count:0,average_rating:0,postal_code:"4000"}]);expect(s.itemListElement[0].item).not.toHaveProperty("aggregateRating");expect(s.itemListElement[0].item).not.toHaveProperty("address");});
test("list count describes bounded emitted items and escaping prevents script breakout",()=>{const s=generateCategoryListSchema("spa",Array.from({length:25},(_,i)=>({name:"</script><script>bad &",slug:String(i)})));expect(s.numberOfItems).toBe(20);expect(s.itemListElement).toHaveLength(20);const encoded=safeJsonLd(s);expect(encoded).not.toContain("<");expect(JSON.parse(encoded).itemListElement[0].item.name).toBe("</script><script>bad &");});
test.each(["de","en","fr","it"])("%s website and organization use existing destinations",locale=>{expect(generateWebsiteSchema(locale).potentialAction.target.urlTemplate).toBe(`https://solen.ch/${locale}/search?q={search_term_string}`);expect(generateOrganizationSchema(locale).url).toBe(`https://solen.ch/${locale}`);});
