#!/usr/bin/env node
//
// Generates _inventory/SURFACE.md + _inventory/SURFACE.json from the LIVE repo.
//   Run:  npm run inventory
//
// "What exists" is generated from the filesystem on every run, so the map cannot rot the
// way the hand-written inventories (UTILITIES_INDEX, KEY_FEATURES, ...) did. For semantic
// status (partial / deprecated / don't-reuse) see the hand-maintained _inventory/STATUS.md.

import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import {
  scanRoutes,
  scanEndpoints,
  scanComponents,
  scanLib,
  scanRpcs,
  loadDbTables,
  loadDbColumns,
  REPO_ROOT,
} from "./lib/scan-surface.mjs";

const CHECK = process.argv.includes("--check"); // CI mode: verify freshness, don't write

const routes = scanRoutes();
const endpoints = scanEndpoints();
const components = scanComponents();
const lib = scanLib();
const rpcs = scanRpcs();
const db = loadDbTables();
const dbc = loadDbColumns();

const outDir = join(REPO_ROOT, "_inventory");
mkdirSync(outDir, { recursive: true });

// ---- machine-readable ----
const jsonStr = JSON.stringify(
  {
    _note: "AUTO-GENERATED by scripts/inventory.mjs. Do not edit by hand. Run `npm run inventory`.",
    counts: {
      routes: routes.length,
      endpoints: endpoints.length,
      components: components.length,
      lib: lib.length,
      rpcs: rpcs.length,
      tables: db.tables?.length ?? 0,
      columns: Object.values(dbc.byTable || {}).reduce((n, c) => n + c.length, 0),
    },
    routes,
    endpoints,
    components,
    lib,
    rpcs,
    db,
    dbColumns: dbc.byTable,
  },
  null,
  2,
);

// ---- human-scannable ----
const L = [];
const p = (s = "") => L.push(s);

p("# Solen Surface Map — what EXISTS");
p("");
p("> 🤖 **AUTO-GENERATED — do not edit by hand.** Run `npm run inventory` to regenerate.");
p(">");
p("> This is the source of truth for *what exists*. **Before building any new page / endpoint /");
p("> component / table, check here or run `npm run exists <keyword>`.** When the map is silent,");
p("> the thing genuinely does not exist — build it. When it has a hit, REUSE or EXTEND.");
p(">");
p("> For *status* (partial · deprecated · don't-reuse-for) see `_inventory/STATUS.md` (hand-kept).");
p("");
p(
  `**Totals:** ${routes.length} routes · ${endpoints.length} API endpoints · ${components.length} components · ${lib.length} lib/hooks modules · ${rpcs.length} DB functions · ${db.tables?.length ?? 0} DB tables · ${Object.values(dbc.byTable || {}).reduce((n, c) => n + c.length, 0)} columns indexed`,
);
p("");

p("## Routes (pages)");
p("");
p("| URL | File |");
p("|---|---|");
for (const r of routes) p(`| \`${r.url}\` | \`${r.file}\` |`);
p("");

p("## API endpoints");
p("");
p("| Endpoint | Methods | File |");
p("|---|---|---|");
for (const e of endpoints) p(`| \`${e.url}\` | ${e.methods.join(", ")} | \`${e.file}\` |`);
p("");

p("## DB tables (live snapshot)");
p("");
if (db.capturedAt)
  p(`_Snapshot ${db.capturedAt} · schema \`${db.schema || "public"}\` · via live Supabase introspection (NOT migration files, which drift)._`);
else p(`_⚠️ ${db.note || "no snapshot loaded"}._`);
p("");
if (db.tables?.length) {
  p("| Table | Rows | RLS |");
  p("|---|---|---|");
  for (const t of db.tables) p(`| \`${t.name}\` | ${t.rows ?? "?"} | ${t.rls ? "on" : "**OFF**"} |`);
  p("");
  if (db.rlsDisabled?.length) {
    p(`> ⚠️ **${db.rlsDisabled.length} tables have RLS OFF** (anon key can read/write): ${db.rlsDisabled.map((t) => `\`${t}\``).join(", ")}.`);
    p("");
  }
  if (dbc.capturedAt) p(`_Columns are indexed in \`_inventory/_db-columns.json\` and searchable: \`npm run exists <column>\`._`);
  p("");
}

p("## DB functions / RPCs");
p("");
p("_Defined in `supabase/migrations/`. Call from app code via `supabase.rpc('<name>')`._");
p("");
p("| Function | First defined in |");
p("|---|---|");
for (const r of rpcs) p(`| \`${r.name}\` | \`${r.file}\` |`);
p("");

p("## Components");
p("");
p(`<details><summary>${components.length} components — click to expand</summary>`);
p("");
p("| Component | File |");
p("|---|---|");
for (const c of components) p(`| ${c.name} | \`${c.file}\` |`);
p("");
p("</details>");
p("");

p("## lib/ modules");
p("");
p(`<details><summary>${lib.length} modules — click to expand</summary>`);
p("");
p("| Module | File |");
p("|---|---|");
for (const m of lib) p(`| ${m.name} | \`${m.file}\` |`);
p("");
p("</details>");
p("");

const mdStr = L.join("\n") + "\n";

// Snapshot freshness (DB snapshot is hand-refreshed; flag if it has aged out).
const SNAPSHOT_MAX_AGE_DAYS = 30;
let ageDays = null;
if (db.capturedAt) {
  ageDays = Math.floor((Date.now() - Date.parse(db.capturedAt)) / 86_400_000);
}

if (CHECK) {
  // CI mode: verify the committed map matches a fresh scan, and the snapshot isn't stale.
  const problems = [];
  for (const [name, fresh] of [["SURFACE.json", jsonStr + "\n"], ["SURFACE.md", mdStr]]) {
    const path = join(outDir, name);
    const committed = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (committed !== fresh) problems.push(`${name} is stale`);
  }
  if (ageDays !== null && ageDays > SNAPSHOT_MAX_AGE_DAYS) {
    problems.push(`DB snapshot is ${ageDays}d old (> ${SNAPSHOT_MAX_AGE_DAYS}d) — \`exists <table|column>\` may be wrong`);
  }
  if (problems.length) {
    console.error("✗ inventory check FAILED:");
    for (const p2 of problems) console.error(`  - ${p2}`);
    console.error("\nFix: run `npm run inventory` (and/or refresh _inventory/_db-snapshot.json + _db-columns.json), then commit.");
    process.exit(1);
  }
  console.log(`✓ inventory fresh — SURFACE.md/json match the live tree; DB snapshot ${ageDays}d old (≤ ${SNAPSHOT_MAX_AGE_DAYS}d)`);
  process.exit(0);
}

writeFileSync(join(outDir, "SURFACE.json"), jsonStr + "\n");
writeFileSync(join(outDir, "SURFACE.md"), mdStr);

console.log("✓ _inventory/SURFACE.md + SURFACE.json");
console.log(
  `  ${routes.length} routes · ${endpoints.length} endpoints · ${components.length} components · ${lib.length} lib/hooks · ${rpcs.length} RPCs · ${db.tables?.length ?? 0} tables`,
);
if (!db.capturedAt) console.log(`  ⚠️  no DB snapshot (${db.note}) — tables omitted`);
else if (ageDays > SNAPSHOT_MAX_AGE_DAYS) console.log(`  ⚠️  DB snapshot is ${ageDays}d old — refresh it`);
