#!/usr/bin/env node
//
// Generates _inventory/SURFACE.md + _inventory/SURFACE.json from the LIVE repo.
//   Run:  npm run inventory
//
// "What exists" is generated from the filesystem on every run, so the map cannot rot the
// way the hand-written inventories (UTILITIES_INDEX, KEY_FEATURES, ...) did. For semantic
// status (partial / deprecated / don't-reuse) see the hand-maintained _inventory/STATUS.md.

import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import {
  scanRoutes,
  scanEndpoints,
  scanComponents,
  scanLib,
  scanRpcs,
  loadDbTables,
  loadDbColumns,
  REPO_ROOT,
} from "./lib/scan-surface.mjs";
import { computeStuckRows, STUCK_ROWS_MAX_AGE_DAYS } from "./lib/stuck-rows.mjs";

const CHECK = process.argv.includes("--check"); // CI mode: verify freshness, don't write

const routes = scanRoutes();
const endpoints = scanEndpoints();
const components = scanComponents();
const lib = scanLib();
const rpcs = scanRpcs();
const db = loadDbTables();
const dbc = loadDbColumns();

const outDir = join(REPO_ROOT, "_inventory");
mkdirSync(outDir, { recursive: true });

// ---- stuck rows (data health) ----
// CHECK mode never hits the live DB (no credentials in CI, and --check's own contract is
// "verify freshness, don't write"). It only reads back whatever was already committed, so a
// stale committed report is caught without needing a live connection.
const stuckRowsPath = join(outDir, "_stuck-rows.json");
let stuckRows;
if (CHECK) {
  if (existsSync(stuckRowsPath)) {
    try {
      stuckRows = JSON.parse(readFileSync(stuckRowsPath, "utf8"));
    } catch {
      stuckRows = { generatedAt: null, error: "committed _stuck-rows.json unreadable (bad JSON)" };
    }
  } else {
    stuckRows = { generatedAt: null, error: "no committed _stuck-rows.json yet, run `npm run inventory`" };
  }
} else {
  stuckRows = await computeStuckRows(REPO_ROOT);
}
const stuckRowsAgeDays = stuckRows.generatedAt
  ? Math.floor((Date.now() - Date.parse(stuckRows.generatedAt)) / 86_400_000)
  : null;

// ---- machine-readable ----
const jsonStr = JSON.stringify(
  {
    _note: "AUTO-GENERATED by scripts/inventory.mjs. Do not edit by hand. Run `npm run inventory`.",
    counts: {
      routes: routes.length,
      endpoints: endpoints.length,
      components: components.length,
      lib: lib.length,
      rpcs: rpcs.length,
      tables: db.tables?.length ?? 0,
      columns: Object.values(dbc.byTable || {}).reduce((n, c) => n + c.length, 0),
    },
    routes,
    endpoints,
    components,
    lib,
    rpcs,
    db,
    dbColumns: dbc.byTable,
  },
  null,
  2,
);

// ---- human-scannable ----
const L = [];
const p = (s = "") => L.push(s);

p("# Solen Surface Map — what EXISTS");
p("");
p("> 🤖 **AUTO-GENERATED — do not edit by hand.** Run `npm run inventory` to regenerate.");
p(">");
p("> This is the source of truth for *what exists*. **Before building any new page / endpoint /");
p("> component / table, check here or run `npm run exists <keyword>`.** When the map is silent,");
p("> the thing genuinely does not exist — build it. When it has a hit, REUSE or EXTEND.");
p(">");
p("> For *status* (partial · deprecated · don't-reuse-for) see `_inventory/STATUS.md` (hand-kept).");
p("");
p(
  `**Totals:** ${routes.length} routes · ${endpoints.length} API endpoints · ${components.length} components · ${lib.length} lib/hooks modules · ${rpcs.length} DB functions · ${db.tables?.length ?? 0} DB tables · ${Object.values(dbc.byTable || {}).reduce((n, c) => n + c.length, 0)} columns indexed`,
);
p("");
p(
  "**Live data health:** `_inventory/STUCK_ROWS.md` (auto-generated by this same command) reports rows stuck past the point they should have moved on, e.g. walk-in tickets never closed out, bookings never confirmed. Read it before trusting any count computed over live rows.",
);
p("");

p("## Routes (pages)");
p("");
p("| URL | File |");
p("|---|---|");
for (const r of routes) p(`| \`${r.url}\` | \`${r.file}\` |`);
p("");

p("## API endpoints");
p("");
p("| Endpoint | Methods | File |");
p("|---|---|---|");
for (const e of endpoints) p(`| \`${e.url}\` | ${e.methods.join(", ")} | \`${e.file}\` |`);
p("");

p("## DB tables (live snapshot)");
p("");
if (db.capturedAt)
  p(`_Snapshot ${db.capturedAt} · schema \`${db.schema || "public"}\` · via live Supabase introspection (NOT migration files, which drift)._`);
else p(`_⚠️ ${db.note || "no snapshot loaded"}._`);
p("");
if (db.tables?.length) {
  p("| Table | Rows | RLS |");
  p("|---|---|---|");
  for (const t of db.tables) p(`| \`${t.name}\` | ${t.rows ?? "?"} | ${t.rls ? "on" : "**OFF**"} |`);
  p("");
  if (db.rlsDisabled?.length) {
    p(`> ⚠️ **${db.rlsDisabled.length} tables have RLS OFF** (anon key can read/write): ${db.rlsDisabled.map((t) => `\`${t}\``).join(", ")}.`);
    p("");
  }
  if (dbc.capturedAt) p(`_Columns are indexed in \`_inventory/_db-columns.json\` and searchable: \`npm run exists <column>\`._`);
  p("");
}

p("## DB functions / RPCs");
p("");
p("_Defined in `supabase/migrations/`. Call from app code via `supabase.rpc('<name>')`._");
p("");
p("| Function | First defined in |");
p("|---|---|");
for (const r of rpcs) p(`| \`${r.name}\` | \`${r.file}\` |`);
p("");

p("## Components");
p("");
p(`<details><summary>${components.length} components — click to expand</summary>`);
p("");
p("| Component | File |");
p("|---|---|");
for (const c of components) p(`| ${c.name} | \`${c.file}\` |`);
p("");
p("</details>");
p("");

p("## lib/ modules");
p("");
p(`<details><summary>${lib.length} modules — click to expand</summary>`);
p("");
p("| Module | File |");
p("|---|---|");
for (const m of lib) p(`| ${m.name} | \`${m.file}\` |`);
p("");
p("</details>");
p("");

const mdStr = L.join("\n") + "\n";

// ---- stuck rows, human-scannable ----
// Rendered fresh every write run (never reused across runs), so "generated" always means
// "true as of this run". A reader opening a committed copy later judges staleness themselves
// off the printed timestamp; the CHECK block below also warns dynamically off the same field.
function renderStuckRowsMd(sr) {
  const SL = [];
  const sp = (s = "") => SL.push(s);
  sp("# Stuck rows, data health");
  sp("");
  sp("> Auto-generated by `npm run inventory`. Read-only report, no row is written or deleted to produce it.");
  sp("");
  const genLocal = sr.generatedAt
    ? new Date(sr.generatedAt).toUTCString()
    : "unknown (this report has never run successfully)";
  sp(`**Generated:** ${sr.generatedAt ?? "never"} (${genLocal}).`);
  sp(
    `If you are reading this more than ${STUCK_ROWS_MAX_AGE_DAYS} days after that timestamp, treat every number below as taken that long ago and possibly out of date. Re-run \`npm run inventory\` before trusting it.`,
  );
  sp("");
  if (sr.error) {
    sp(`**Could not produce this report:** ${sr.error}`);
    sp("");
    return SL.join("\n") + "\n";
  }
  for (const c of sr.checks || []) {
    sp(`## ${c.label}`);
    sp("");
    if (c.error) {
      sp(`Could not run this check: ${c.error}`);
      sp("");
      continue;
    }
    sp(`**${c.count} row${c.count === 1 ? "" : "s"}.**`);
    if (c.oldest) {
      const salon = c.oldest.salonName
        ? `salon "${c.oldest.salonName}" (id \`${c.oldest.salonId}\`)`
        : c.oldest.salonId
          ? `salon id \`${c.oldest.salonId}\``
          : "no salon on the row";
      sp(
        `Oldest: \`${c.oldest.id}\`, dated ${c.oldest.date} (${c.oldest.daysOld} day${c.oldest.daysOld === 1 ? "" : "s"} ago), ${salon}.`,
      );
    }
    sp("");
  }
  return SL.join("\n") + "\n";
}

// Snapshot freshness (DB snapshot is hand-refreshed; flag if it has aged out).
const SNAPSHOT_MAX_AGE_DAYS = 30;
let ageDays = null;
if (db.capturedAt) {
  ageDays = Math.floor((Date.now() - Date.parse(db.capturedAt)) / 86_400_000);
}

if (CHECK) {
  // CI mode: verify the committed map matches a fresh scan, and the snapshot isn't stale.
  const problems = [];
  // Stuck-rows freshness is a WARNING here, not a build failure: CI has no Supabase
  // credentials (.github/workflows/inventory-freshness.yml runs dependency-free, no secrets
  // configured), so this job cannot regenerate a fresh one to compare against. It can only
  // tell whoever is watching CI that the committed report is aging, same as the console
  // warning a local write run prints off this identical field.
  if (stuckRowsAgeDays !== null && stuckRowsAgeDays > STUCK_ROWS_MAX_AGE_DAYS) {
    console.warn(
      `WARNING: _inventory/_stuck-rows.json is ${stuckRowsAgeDays}d old (more than ${STUCK_ROWS_MAX_AGE_DAYS}d), taken that long ago, may be out of date. Run \`npm run inventory\` locally (needs .env.local) to refresh.`,
    );
  } else if (stuckRows.error) {
    console.warn(`WARNING: _inventory/_stuck-rows.json: ${stuckRows.error}`);
  }
  for (const [name, fresh] of [["SURFACE.json", jsonStr + "\n"], ["SURFACE.md", mdStr]]) {
    const path = join(outDir, name);
    const committed = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (committed !== fresh) problems.push(`${name} is stale`);
  }
  if (ageDays !== null && ageDays > SNAPSHOT_MAX_AGE_DAYS) {
    problems.push(`DB snapshot is ${ageDays}d old (> ${SNAPSHOT_MAX_AGE_DAYS}d) — \`exists <table|column>\` may be wrong`);
  }
  if (problems.length) {
    console.error("✗ inventory check FAILED:");
    for (const p2 of problems) console.error(`  - ${p2}`);
    console.error("\nFix: run `npm run inventory` (and/or refresh _inventory/_db-snapshot.json + _db-columns.json), then commit.");
    process.exit(1);
  }
  console.log(`✓ inventory fresh — SURFACE.md/json match the live tree; DB snapshot ${ageDays}d old (≤ ${SNAPSHOT_MAX_AGE_DAYS}d)`);
  process.exit(0);
}

writeFileSync(join(outDir, "SURFACE.json"), jsonStr + "\n");
writeFileSync(join(outDir, "SURFACE.md"), mdStr);
writeFileSync(join(outDir, "_stuck-rows.json"), JSON.stringify(stuckRows, null, 2) + "\n");
writeFileSync(join(outDir, "STUCK_ROWS.md"), renderStuckRowsMd(stuckRows));

console.log("✓ _inventory/STUCK_ROWS.md + _stuck-rows.json");
if (stuckRows.error) {
  console.log(`  WARNING: ${stuckRows.error}`);
} else {
  for (const c of stuckRows.checks || []) {
    if (c.error) console.log(`  WARNING: ${c.table}: ${c.error}`);
    else console.log(`  ${c.table}: ${c.count} stuck row${c.count === 1 ? "" : "s"}${c.oldest ? `, oldest ${c.oldest.daysOld}d old` : ""}`);
  }
}

console.log("✓ _inventory/SURFACE.md + SURFACE.json");
console.log(
  `  ${routes.length} routes · ${endpoints.length} endpoints · ${components.length} components · ${lib.length} lib/hooks · ${rpcs.length} RPCs · ${db.tables?.length ?? 0} tables`,
);
if (!db.capturedAt) console.log(`  ⚠️  no DB snapshot (${db.note}) — tables omitted`);
else if (ageDays > SNAPSHOT_MAX_AGE_DAYS) console.log(`  ⚠️  DB snapshot is ${ageDays}d old — refresh it`);
