ALTER TABLE profiles ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS age_range TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hair_type TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hair_length TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS preferred_services TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS neighbourhood TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS profile_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
