CREATE TABLE IF NOT EXISTS platform_stats (
  key TEXT PRIMARY KEY,
  value NUMERIC DEFAULT 0,
  computed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE salons ADD COLUMN IF NOT EXISTS explore_score NUMERIC(5,2) DEFAULT 0;
