-- exists-check: `npm run exists lost_dispute_id` -> 0 matches, `npm run exists dispute_id`
-- -> 2 matches (case_events.dispute_id, warnings.dispute_id), neither is this column or this
-- table. `npm run exists "salon_payouts dispute_lost"` -> 0 matches. Net-new column on
-- salon_payouts.
-- Ring 8b (backend improvement loop): charge.dispute.closed 'lost' branch CAS idempotency
-- marker.
--
-- NOT YET applied live as of this commit (the orchestrator applies it, additive, idempotent
-- ADD COLUMN IF NOT EXISTS) before the webhook code that reads/writes it ships. Until
-- applied, the webhook's CAS write degrades gracefully (a PostgREST schema-cache error on
-- the UPDATE is caught + logged, the decrement is simply skipped rather than applied
-- unguarded, never blocking the audit-log write next to it or reopening the bug this column
-- exists to close; see app/api/stripe/webhook/route.ts, the charge.dispute.closed 'lost'
-- branch).
--
-- Context: app/api/stripe/webhook/route.ts:611-621 (as flagged by the ring 8 reviewer) read
-- the CURRENT salon_payouts row and subtracted dispute.amount from it. charge.refunded is
-- safe doing this because Stripe hands it a cumulative, Stripe-tracked fact on the charge
-- itself (charge.amount_refunded, the running total across every refund on that charge), so
-- recomputing from the event's own payload converges no matter how many times the event (or
-- its retry) runs. The charge.dispute.closed event carries no equivalent cumulative
-- "amount disputed" fact, only the fixed dispute.amount for this one dispute, and fetching
-- one would require an extra Stripe API call this webhook handler intentionally avoids. So
-- decrementing off the CURRENT row was only correct on the FIRST delivery: a claim-release
-- retry (app/api/stripe/webhook/route.ts's processed_webhook_events claim is released on any
-- handler error, so Stripe can and does re-run the full handler body) after the write had
-- already committed once would decrement AGAIN off the already-lowered value, silently
-- underpaying the salon.
--
-- lost_dispute_id is a CAS-claimed idempotency marker, not a second ledger field: the
-- webhook claims the decrement AND this marker in the SAME UPDATE, gated on
-- lost_dispute_id IS NULL, so only the first delivery for a given dispute.id can ever mutate
-- the row. A charge can carry at most one dispute over its lifetime (Stripe does not allow
-- re-disputing an already-disputed charge), so a single nullable text column is sufficient,
-- no array/child-table needed. Additive + idempotent (project rule: never
-- supabase db push/reset; ADD COLUMN IF NOT EXISTS only).
alter table public.salon_payouts add column if not exists lost_dispute_id text;
comment on column public.salon_payouts.lost_dispute_id is
  'CAS-claimed once by the Stripe webhook (charge.dispute.closed, status=lost) the first time it decrements this payout row for a given Stripe dispute id. NOT a second ledger amount, an idempotency marker only: claimed via UPDATE ... WHERE lost_dispute_id IS NULL in the SAME statement as the gross/commission/net decrement, so a webhook retry (claim-release-and-redeliver) or a genuine Stripe redelivery of the same event is a safe no-op instead of double-decrementing the salon payout.';
